- name: Create database user {{ mastodon_user }}
  postgresql_user:
    name: "{{ mastodon_db_user }}"
    password: "{{ mastodon_db_password }}"
    role_attr_flags: CREATEDB

- name: Create database {{ mastodon_db }}
  postgresql_db:
    name: "{{ mastodon_db }}"
